### PR TITLE
Play! 1.4.x: Update dependencies.xml for Play! 1.4.6 compatibility

### PR DESCRIPTION
**Pull request by gregorkistler**
Fix for:

```
~ *****************************************************************************
~
~ WARNING: These dependencies are missing, your application may not work properly (use --verbose for details),
~
~
~
~	play->play [1.3.4,1.4[
~
~	play->play [1.3.4,1.4[: not found
~
~ *****************************************************************************
~
~ Some dependencies are still missing.
```

### CODE REVIEW

**Comment by xabolcs** [comment]
Update commit title to: `Upgrade Play! to 1.4.6 (see openseedbox/openseedbox#77)`

**Comment by gregorkistler** [comment]
Done

**Comment by xabolcs** [comment]
> Done

It isn't! :stuck_out_tongue: 

While `openseedbox-common`'s commit message equals to `openseedbox-server`'s but they are different from `openseedbox`'.

Let me handle these! :+1:

**Comment by xabolcs** [comment]
Landed as commit 944ce36ad1b4e17199316712df9f8a538d0a301f.

**Comment by gregorkistler** [comment]
> > Done
> 
> It isn't! 😛
> 
> While `openseedbox-common`'s commit message equals to `openseedbox-server`'s, they are different from `openseedbox`'.
> 
> Let me handle these! 👍

True, only checked the first two and did copy&paste 🙈
Thanks!

**Pull request closed without merging**
